apiVersion: apps/v1
kind: Deployment
metadata:
  name: design74-mongodb
  namespace: design74-infrastructure
  labels:
    app: design74-mongodb
    component: database
    project: design74
spec:
  replicas: 1
  selector:
    matchLabels:
      app: design74-mongodb
  template:
    metadata:
      labels:
        app: design74-mongodb
        component: database
        project: design74
    spec:
      containers:
      - name: mongodb
        image: mongo:7.0
        ports:
        - containerPort: 27017
          name: mongodb
        env:
        - name: MONGO_INITDB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: design74-shared-config
              key: MONGODB_DATABASE_NAME
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
        - name: mongodb-config
          mountPath: /data/configdb
        livenessProbe:
          exec:
            command:
            - mongosh
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 15
          failureThreshold: 5
        readinessProbe:
          exec:
            command:
            - mongosh
            - --eval
            - "db.adminCommand('ping')"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: design74-mongodb-data-pvc
      - name: mongodb-config
        persistentVolumeClaim:
          claimName: design74-mongodb-config-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: design74-mongodb
  namespace: design74-infrastructure
  labels:
    app: design74-mongodb
    component: database
    project: design74
    port-forward: "enabled"
  annotations:
    port-forward.design74.io/ports: "27017"
    port-forward.design74.io/description: "MongoDB database access"
spec:
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongodb
  selector:
    app: design74-mongodb
