apiVersion: apps/v1
kind: Deployment
metadata:
  name: design74-prometheus
  namespace: design74-infrastructure
  labels:
    app: design74-prometheus
    component: metrics
    project: design74
spec:
  replicas: 1
  selector:
    matchLabels:
      app: design74-prometheus
  template:
    metadata:
      labels:
        app: design74-prometheus
        component: metrics
        project: design74
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v2.47.0
        ports:
        - containerPort: 9090
          name: http
        args:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.console.libraries=/etc/prometheus/console_libraries'
        - '--web.console.templates=/etc/prometheus/consoles'
        - '--storage.tsdb.retention.time=200h'
        - '--web.enable-lifecycle'
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
        - name: prometheus-data
          mountPath: /prometheus
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: 9090
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /-/ready
            port: 9090
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: prometheus-config
        configMap:
          name: design74-prometheus-config
      - name: prometheus-data
        persistentVolumeClaim:
          claimName: design74-prometheus-data-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: design74-prometheus
  namespace: design74-infrastructure
  labels:
    app: design74-prometheus
    component: metrics
    project: design74
    port-forward: "enabled"
  annotations:
    port-forward.design74.io/ports: "9090"
    port-forward.design74.io/description: "Prometheus metrics and monitoring"
spec:
  type: ClusterIP
  ports:
  - port: 9090
    targetPort: 9090
    name: http
  selector:
    app: design74-prometheus
